version: '2'
services:
  db:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
      - "1434:1434/udp"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
